insert into teams (season_year, owner_id, team_name)
select v.season_year, o.owner_id, v.team_name
from (values
    (2022, 'josh',   'Faith + 1'),
    (2022, 'chris',  'Handcuff my Cousins'),
    (2022, 'joey',   'Acorns'),
    (2022, 'tulio',  'Armed Rodgery'),
    (2022, 'tom',    'Get Swifty'),
    (2022, 'david',  'Sutton for Punishment'),
    (2022, 'theo',   'TEBOW MANIA!!!'),
    (2022, 'matt',   'Finkle''s the Mayor'),
    (2022, 'carter', 'Coach Carter'),
    (2022, 'borys',  'ConcRussed'),
    (2022, 'laura',  'Questionable'),
    (2022, 'curtis', 'Tua for the Show'),

    (2023, 'joey',   'Acorns'),
    (2023, 'borys',  'CeeDeezNutz'),
    (2023, 'carter', 'Coach Carter'),
    (2023, 'laura',  'Dak to December'),
    (2023, 'josh',   'Faith + 1'),
    (2023, 'matt',   'Finkle is the Mayor'),
    (2023, 'chris',  'Geriatric Pickens'),
    (2023, 'david',  'Jefferson Starship'),
    (2023, 'tulio',  'One Tyreek Hill'),
    (2023, 'tom',    'Tall Glass of Charbonnet'),
    (2023, 'theo',   'TEBOW MANIA!!!'),
    (2023, 'curtis', 'Tua Salad with Bijan Mustard'),

    (2024, 'joey',   'Acorns'),
    (2024, 'borys',  'Big Penix Energy'),
    (2024, 'tom',    'Caleb Will-yum-yums'),
    (2024, 'josh',   'Faith + 1'),
    (2024, 'matt',   'Finkle is the Mayor'),
    (2024, 'laura',  'Go Long London'),
    (2024, 'niall',  'Niall''s Fraud Team'),
    (2024, 'tulio',  'One Tyreek Hill'),
    (2024, 'carter', 'Re-Mixon a thing called Love'),
    (2024, 'chris',  'Scary Terry'),
    (2024, 'curtis', 'Tua Salad with Bijan Mustard'),
    (2024, 'david',  'Work from Mahomes'),

    (2025, 'tom',    '2 TEs 1 Cup'),
    (2025, 'joey',   'Acorns'),
    (2025, 'tulio',  'Catch Me If You Cook'),
    (2025, 'borys',  'Ceedeez Nutz'),
    (2025, 'matt',   'Finkle is the Mayor'),
    (2025, 'laura',  'Go Long London'),
    (2025, 'carter', 'Hall the Love in the world'),
    (2025, 'josh',   'It''s Me Mr. Jaxon! Hee-Hee!'),
    (2025, 'chris',  'I''m stuck Step-Burrow'),
    (2025, 'curtis', 'Life of a Bo Girl'),
    (2025, 'david',  'Work from Mahomes'),
    (2025, 'niall',  'Zac Robinson is a Terrorist'),

    (2026, 'tom',    '2 TEs 1 Cup'),
    (2026, 'joey',   'Acorns'),
    (2026, 'tulio',  'Catch Me If You Cook'),
    (2026, 'borys',  'Ceedeez Nutz'),
    (2026, 'matt',   'Finkle is the Mayor'),
    (2026, 'laura',  'Go Long London'),
    (2026, 'carter', 'Hall the Love in the world'),
    (2026, 'josh',   'It''s Me Mr. Jaxon! Hee-Hee!'),
    (2026, 'chris',  'I''m stuck Step-Burrow'),
    (2026, 'curtis', 'Life of a Bo Girl'),
    (2026, 'david',  'Work from Mahomes'),
    (2026, 'niall',  'Zac Robinson is a Terrorist')
) as v (season_year, username, team_name)
join owners o on lower(o.username) = v.username;
